---
# Base path for all templates
template_base_path: "{{ playbook_dir }}/app-configs"
# Vault server address
vault_addr: "https://vault.trez.wtf"
vault_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31626632653338353037663066643261383134343463313661396666363330623863306337333136
  3039653965666131653536656363336466393266653363630a306334393865613430303737636233
  37303365396566306637643735383861633164336462663134363561666430613562323966353732
  6335353137303161390a303530333635636136393364386636663731353234633762376136316434
  34366464363762633937613837393931363237376466616164363465363338343937623737376332
  38336134393661303530613439343433336634653264663266653030346664316231636431313936
  62396630376330353132303763333430346536323431623835343934323338303066356438396436
  37306632616261363863313235336432656266656463333135333163333635356262373033323032
  3064
