---
# Base path for all templates
template_base_path: "{{ playbook_dir }}/app-configs"
# Vault server address
vault_addr: "https://vault.trez.wtf"
vault_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37653866643538383634623965613234353864386336623939383233633265633130366239626439
  3932353431313731343232393165343836633433346339310a643430326235393162643337643565
  32666334383863313961393866616135653464653862336434643832663038643737376165653837
  3065653661316564620a343363613662633031336235396534616635373734393361353461363131
  36383131363339343134313835663536323865663761356236356638366662653165626665393036
  64393361643938393432626439656432643966316466643739623339666538643862333263323733
  39393832643537386537396230663931316562633736643732643630623632313537383561376639
  39643164343938396432393231393263376230323530623761636261323630636535356339666433
  6138
