---
# Base path for all templates
template_base_path: "{{ playbook_dir }}/app-configs"
# Vault server address
vault_addr: "https://vault.trez.wtf"
vault_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31386335336463633735623162613537393463393064393062626636343363636131633634666433
  3634316561633766613436346233333932353763656631360a366266643366636337336338613834
  61353833663862346533303135363531646166623138613563373738646637303437373264613765
  3363393563653637310a363736663232643066356266316535393265376236663635353065636138
  34303935383661633364393864656135323639336463323736653866643238356166356139623733
  37623438353739343565646464666433656465373135643562383163383862646435393564353166
  37306663646339313330383465393937353830643235666362393630643065336161363434316563
  64633563363465313165393461393866313662346135313139363436363365643839643839323532
  3264
