appdata_base_path: /home/charish/.docker/config/appdata
ansible_become_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30646333393563333364333935396530353265616233323839616266653938396561343539336337
  6531313061626132636362373833356631336161626435660a643539353930396532653234393663
  31623863633966303738643733643633353265396264613734333461643862663965663230663437
  6136373035303834630a653263626365623838363236303931643565656232326536643239653238
  64313034313663653332343464383565383964373438663661346538366636323162
secrets_path: rinoa-docker/env
file_metadata:
  "hashicorp-vault/config/vault-config.hcl.j2":
    owner: "100"
    group: "1000"
    mode: "0644"
  "mongodb/config/keyfile.j2":
    owner: "999"
    group: "999"
    mode: "0600"
  "searxng/settings.yml.j2":
    owner: "977"
    group: "977"
    mode: "0644"
  "searxng/uwsgi.ini.j2":
    owner: "977"
    group: "977"
    mode: "0644"
