appdata_base_path: /home/charish/.config/docker
ansible_become_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35623531633464343532353539366432373931633465363832383735643665636534646131313135
  3535376663383166343933373463643862316635663531610a646565346335313932323566386330
  64356164313763666663393034343435353633313963306437613333356266303761313863396166
  6530663063363831630a376466623331346364306163626438666339666563323332623738336464
  37643137656336373230613737343530306131663039303630623063333937653333
secrets_path: ultima-docker/env
