appdata_base_path: /home/charish/.config/docker
ansible_become_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37363634303539386437373433653834326537613239373539383731333364316461373436646233
  3965616330356537666537323433666339653166616361370a616639363432643964343131636265
  64623239343238363763386466626632383230633062383263323433353634373539373861383038
  3837383436363138330a653566653731653065343538363733353432646136336335643666376133
  31623634636561636635396136636538613338313862396439376435613337373637
secrets_path: ultima-docker/env
